# Generated by Django 3.1.2 on 2020-10-11 18:22

import User_Auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTokens',
            fields=[
                ('id', models.CharField(default=User_Auth.models.generate_id, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User_Auth.signupmodel')),
            ],
        ),
    ]
