# Generated by Django 3.1.2 on 2020-10-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0002_authtokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authtokens',
            old_name='user',
            new_name='username',
        ),
    ]
