# Generated by Django 3.1.2 on 2020-10-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0003_auto_20201012_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='expiry_window',
            field=models.IntegerField(default=300),
        ),
    ]
