# Generated by Django 3.1.2 on 2020-10-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0004_signupmodel_expiry_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
