# Generated by Django 3.1.2 on 2020-10-11 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0005_signupmodel_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authtokens',
            old_name='username',
            new_name='user',
        ),
    ]
